VIOLATION_WEIGHTS = {
    "NO PARKING": 0.50,
    "WRONG PARKING": 0.60,
    "PARKING ON FOOTPATH": 0.70,
    "DOUBLE PARKING": 0.80,
    "PARKING IN A MAIN ROAD": 0.90,
    "PARKING NEAR ROAD CROSSING": 1.00,
    "PARKING NEAR TRAFFIC LIGHT OR ZEBRA CROSS": 1.00,
    "PARKING NEAR BUSTOP/SCHOOL/HOSPITAL ETC": 0.95,
    "PARKING OTHER THAN BUS STOP": 0.75,
    "PARKING OPPOSITE TO ANOTHER PARKED VEHICLE": 0.85,
}